// Generated by unRap v1.06 by Kegetys

class CfgSounds {

	class MBG_GarageDoor {
		name = "MBG garage door";
		sound[] = {"\MBG_Creationism\s\GarageDoor.ogg", db10, 1.0};
		titles[] = {};
	};
	
	class MBG_OpenDoor {
		name = "MBG open door";
		sound[] = {"\MBG_Creationism\s\OpenDoor.ogg", db10, 1.0};
		titles[] = {};
	};
	
	class MBG_closeDoor {
		name = "MBG open door";
		sound[] = {"\MBG_Creationism\s\closeDoor.ogg", db10, 1.0};
		titles[] = {};
	};
	
	class MBG_mover {
		name = "MBG mover";
		sound[] = {"\MBG_Creationism\s\mover.ogg", db10, 1.0};
		titles[] = {};
	};


	class BB_song_molinos {
		name = "Molinos de viento - Mago de oz";
		sound[] = {"\BB_Songs\sounds\molinos.ogg",db2,1.0};
		titles[] = {};
	};
	class BB_song_rudeboy {
		name = "Dub Inc - Rudeboy";
		sound[] = {"\BB_Songs\sounds\Dub_Inc_Rudeboy.ogg",db2,1.0};
		titles[] = {};
	};

	class BB_song_hardwell {
		name = "House - Hardwell";
		sound[] = {"\BB_Songs\sounds\Hardwell_Dyro_feat_Bright_Lights_Never_Say_Goodbye.ogg",db2,1.0};
		titles[] = {};
	};
	
	class BB_song_masterplan_hod {
		name = "Masterplan - Heart of Darkness";
		sound[] = {"\BB_Songs\sounds\Masterplan_Heart_Of_Darkness.ogg",db2,1.0};
		titles[] = {};
	};

	class BB_song_masterplan_tdr {
		name = "Masterplan - The Dark Road";
		sound[] = {"\BB_Songs\sounds\Masterplan_The_Dark_Road.ogg",db2,1.0};
		titles[] = {};
	};

	class BB_song_WM {
		name = "RTW - Warrior March";
		sound[] = {"\BB_Songs\sounds\Warrior_March.ogg",db2,1.0};
		titles[] = {};
	};

	class BB_song_crom {
		name = "The Anvil Of Crom";
		sound[] = {"\BB_Songs\sounds\The_Anvil_Of_Crom.ogg",db2,1.0};
		titles[] = {};
	};
};
