// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
    class MTVR;	// External class reference
    class Tractor;	// External class reference
    class Ural_CDF;	// External class reference
    class LAV25_HQ;	// External class reference
    class All;	// External class reference
    class Strategic;	// External class reference
    class Ruins;	// External class reference
	class Sound;

    class BB_Base_Object : All {
        scope = private;
        irTarget = "false";
        side = TCivilian;
        icon = "iconStaticObject";
        nameSound = "object";
        simulation = "house";
        picture = "pictureStaticObject";
        model = "";
        sound = "Building";
        placement = "vertical";
        ladders[] = {};
        vehicleClass = "";
        displayName = "";
        coefInside = 1;
        coefInsideHeur = 0.25;
        mapSize = 7.5;
        animated = "false";	// true = model is animated and cannot be assumed static
        armor = 200;
        destrType = "DestructNo";
        damageResistance = 0.004;

    };

	//Objeto que aparece cuando el camion explota para indicar que la base esta abierta
	class HeliHEmpty;
	class BB_Base_Under_Attack: HeliHEmpty{};
	class BB_Song_Oncourse : HeliHEmpty{};


    class BB_Base_Buildable : BB_Base_Object {
        scope = protected;
        model = "";
        displayName = "";
        animated = "true";	// true = model is animated and cannot be assumed static
        vehicleClass = "BB_Buildings";
        nameSound = "house";
        accuracy = 0.2;	// accuracy needed to recognize type of this target
        typicalCargo[] = {};
        destrType = "DestructNo";
        transportAmmo = 0;
        transportRepair = 0;
        transportFuel = 0;
        mapSize = 11;
        cost = 0;
        armor = 800;
    };

    class BB_Buildable_Object : BB_Base_Buildable {
        nameSound = "";
        mapSize = 8;
        accuracy = 1000;	// accuracy needed to recognize type of this target
        armor = 450;
        destrType = "DestructNo";
        scope = public;
    };
	
	class Helipadsmall;
	class BB_Operate_Roof : Helipadsmall{};


    class BB_Stairs_Small : BB_Buildable_Object 
    {
        displayName="Escaleras"; 
        model = "\ca\buildings\podesta_1_stairs4.p3d"; 
        scope = public; 
    };
	
	class BB_Wooden_Planks : BB_Buildable_Object {
        model = "\MBG_Killhouses\m\MBG_Woodplanks.p3d";
        displayName = "BB_Wooden_Planks";
    };

	class BB_Stairs_Small2 : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Treppe250x450x150.p3d";
        displayName = "BB_Stairs_Small2";
    };

	class BB_Small_Wall_H : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Sturz_400x100x25.p3d";
        displayName = "BB_Small_Wall_H";
    };

	class BB_Small_Wall_V : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Wand_100x300x25.p3d";
        displayName = "BB_Small_Wall_V";
    };


    class BB_Small_Roof : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Decke_400x400x25.p3d";
        displayName = "BB_Small_Roof";
    };
	
    //Need mbg killhouses 3
    class BB_Cinderwall : BB_Buildable_Object {
        displayName = "Cinder Wall";
        model = "\MBG_Killhouses\m\MBG_Cinderwall_5.p3d";
    };

    class BB_Small_Wall : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Wand_300x300x25_BetaDMG.p3d";
        displayName = "BB_Small_Wall";
    };

    //Puerta peque - clanAdmin
    class Small_Door : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Tur_300x300x25.p3d";
        displayName = "$STR_AT_TUR_300x300";
		
        class AnimationSources {
            class Open_door {
                source = "user";
                animPeriod = 4;
                initPhase = 0;
            };
        };
		
        class UserActions {
            class Open_Door {
                displayName = "$STR_AT_OpenDoor";
                onlyforplayer = "false";
                position = "Door_knopf";
                radius = 4;
                condition = "((this animationPhase ""Open_door"" < 0.5) and (this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) or bb_admin_activated";
                statement = "this say ""MBG_OpenDoor""; this animate [""Open_door"", 1]";
            };
			
            class Close_Door : Open_Door {
                displayName = "$STR_AT_CloseDoor";
                condition = "this animationPhase ""Open_door"" >= 0.5";
                statement = "this say ""MBG_CloseDoor""; this animate [""Open_door"", 0]";
            };
        };
		
    };
    class Admin_Small_Door : Small_Door {
        class UserActions {
            class Open_Door {
                displayName = "$STR_AT_OpenDoor";
                onlyforplayer = "false";
                position = "Door_knopf";
                radius = 4;
                condition = "(clanAdmin and (this animationPhase ""Open_door"" < 0.5) and (this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) or bb_admin_activated";
                statement = "this say ""MBG_OpenDoor""; this animate [""Open_door"", 1]";
            };
        };
    };
        
    class BB_Wooden_Floor : BB_Buildable_Object {
        model = "\BB_Buildings\m\Suelo_Parket.p3d";
        displayName = "BB_Wooden_Floor";
    };
    //Puerta doble mediana
    class Medium_Door : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Tor_600x300x25.p3d";
        displayName = "$STR_AT_TOR_600x300";
		
        class AnimationSources {
            class Open_Left_Gate {
                source = "user";
                animPeriod = 4;
                initPhase = 0;
            };
			
            class Open_Right_Gate : Open_Left_Gate {};
        };
		
        class UserActions {
            class Open_Gate {
                displayName = "$STR_AT_OpenGate";
                onlyforplayer = "false";
                position = "Door_knopf";
                radius = 4;
                condition = "((this animationPhase ""Open_left_gate"" < 0.5)and (this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) or bb_admin_activated";
                statement = "this animate [""Open_Left_Gate"", 1];this animate [""Open_Right_Gate"", 1]";
            };
			
            class Close_Gate : Open_Gate {
                displayName = "$STR_AT_CloseGate";
                condition = "this animationPhase ""Open_left_gate"" >= 0.5";
                statement = "this animate [""Open_Left_Gate"", 0];this animate [""Open_Right_Gate"", 0]";
            };
        };
    };
    //Puerta Garage grande
    class Garage_Door : BB_Buildable_Object {
        model = "\MBG_Creationism\m\MBG_Tor_900x600x25.p3d";
        displayName = "$STR_AT_TOR_900x600";
		
        class AnimationSources {
            class Left_Segment_1 {
                source = "user";
                animPeriod = 10;
                initPhase = 0;
            };
			
            class Left_Segment_2 : Left_Segment_1 {};
			
            class Left_Segment_3 : Left_Segment_1 {};
			
            class Left_Segment_4 : Left_Segment_1 {};
			
            class Right_Segment_1 : Left_Segment_1 {};
			
            class Right_Segment_2 : Left_Segment_1 {};
			
            class Right_Segment_3 : Left_Segment_1 {};
			
            class Right_Segment_4 : Left_Segment_1 {};
        };
		
        class UserActions {
            class Open_Gate {
                displayName = "$STR_AT_OpenGate";
                onlyforplayer = "false";
                position = "Door_knopf";
                radius = 3;
                condition = "((this animationPhase ""Left_Segment_1"" < 0.5) and (this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) or bb_admin_activated";
                statement = "this say ""MBG_GarageDoor""; this animate [""Left_Segment_1"", 1];this animate [""Left_Segment_2"", 1];this animate [""Left_Segment_3"", 1];this animate [""Left_Segment_4"", 1];this animate [""Right_Segment_1"", 1];this animate [""Right_Segment_2"", 1];this animate [""Right_Segment_3"", 1];this animate [""Right_Segment_4"", 1]";
            };
			
            class Close_Gate : Open_Gate {
                displayName = "$STR_AT_CloseGate";
                condition = "this animationPhase ""Left_Segment_1"" >= 0.5";
                statement = "this say ""MBG_GarageDoor"";this animate [""Left_Segment_1"", 0];this animate [""Left_Segment_2"", 0];this animate [""Left_Segment_3"", 0];this animate [""Left_Segment_4"", 0];this animate [""Right_Segment_1"", 0];this animate [""Right_Segment_2"", 0];this animate [""Right_Segment_3"", 0];this animate [""Right_Segment_4"", 0]";
            };
        };
    };
    
    class Admin_Garage_Door : Garage_Door {
        class UserActions {
            class Open_Gate {
                displayName = "$STR_AT_OpenGate";
                onlyforplayer = "false";
                position = "Door_knopf";
                radius = 3;
                condition = "(clanAdmin and (this animationPhase ""Left_Segment_1"" < 0.5) and (this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) or bb_admin_activated";
                statement = "this say ""MBG_GarageDoor""; this animate [""Left_Segment_1"", 1];this animate [""Left_Segment_2"", 1];this animate [""Left_Segment_3"", 1];this animate [""Left_Segment_4"", 1];this animate [""Right_Segment_1"", 1];this animate [""Right_Segment_2"", 1];this animate [""Right_Segment_3"", 1];this animate [""Right_Segment_4"", 1]";
            };
        };
    };    
        
        
        
    class Infostand_1_EP1;
    class BB_Aux_Panel : Infostand_1_EP1 {
        displayName = "Auxiliar panel";
        vehicleClass = "BB_Buildings";
        class UserActions {
            class Lights_ON {
                displayName="Lights ON";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="true";
                statement = "[this] spawn fnc_lights_on;";
            };
            class Lights_OFF {
                displayName="Lights OFF";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="true";
                statement = "[this] spawn fnc_lights_off;";
            };
            class Alarm_ON {
                displayName="Start alarm system";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!perimeterActivated";
                statement = "[this] spawn fnc_alarm_on;";
            };
            class Alarm_OFF {
                displayName="Stop alarm system";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="perimeterActivated";
                statement = "[] spawn fnc_alarm_off;";
            };
            class Sound_ON {
                displayName="Sound ON";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!soundAlarm";
                statement = "[] spawn fnc_sound_on;";
            };
            class Sound_OFF {
                displayName="Sound OFF";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="soundAlarm";
                statement = "[] spawn fnc_sound_off;";
            };
            class Kill_zombies {
                displayName="Kill zombies (ON/OFF)";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="true";
                statement = "[this] spawn fnc_kill_zombies;";
            };

            class Start_camera {
                displayName="Start camera system";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="true";
                statement = "[this] spawn fnc_start_camera;";
            };
            class explode_gas {
                displayName="Explode gas barrels";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_assault_toxic_gas";
                statement = "[this] spawn fnc_assault_explode_gas;";
            };
        };

    };

    class Infostand_2_EP1;
    class BB_Main_Panel: Infostand_2_EP1 {
        displayName = "Main panel";
        vehicleClass = "BB_Buildings";
        class UserActions {
            class Operate_Roof {
                displayName="Operate Roof";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) || bb_admin_activated"
                statement = "[this] spawn fnc_operate_roof;";
            };
        };
    };
    class FlagPole_EP1;
    class BB_Flag_Pole: FlagPole_EP1 {
        displayName = "Main base flag";
        vehicleClass = "BB_Buildings";
        class UserActions {
            class Authorize {
                displayName="Authorize";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"")) || bb_admin_activated"
                statement = "[this] spawn fnc_authorize;";
            };
        };
    };



    class UralReammo_CDF;
    class BB_Bomb_Truck : UralReammo_CDF {
        displayName = "Bomb truck";
        vehicleClass = "BB_Buildings";
        transportMaxMagazines = 0;
        transportMaxWeapons = 0;
        transportMaxBackpacks = 0;

        class UserActions {
            class Plant_bomb {
                displayName="Plant bomb";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bombTruckActive"
                statement = "[this] spawn plantBombTruckAndOpen;";
            };
        };
    };

    class Land_sara_hasic_zbroj;

    class BB_Yellow_garage : Land_sara_hasic_zbroj {
        displayName = "Yellow garage";
        vehicleClass = "BB_Buildings";
    };

    class Land_A_Castle_Stairs_A;

    class BB_Big_Stairs : Land_A_Castle_Stairs_A {
        displayName = "Big Stairs";
        vehicleClass = "BB_Buildings";
    };

        

    class Land_Hangar_2;
    class BB_Hangar : Land_Hangar_2 {
		
        class UserActions {
            class OpenDoors1 {
                displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_O_DOOR;
                position = "Open_vrata4";
                radius = 3;
                onlyForPlayer = 1;
                condition = "((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"") or bb_admin_activated) and (this animationPhase ""dvere1"" < 0.5)";
                statement = "this animate [""dvere1"", 1]";
            };
			
            class CloseDoors1 {
                displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_C_DOOR;
                position = "Open_vrata4";
                radius = 3;
                onlyForPlayer = 1;
                condition = "(this animationPhase ""dvere1"" >= 0.5) and !(this getVariable[""bb_assaulted"",false])";
                statement = "this animate [""dvere1"", 0]";
            };
            //Esta y la otra estan cambiadas
            class OpenDoors2 {
                displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_C_DOOR;
                position = "Open_vrata4";
                radius = 3;
                onlyForPlayer = 1;
                condition = "(this animationPhase ""dvere2"" > 0.5) and !(this getVariable[""bb_assaulted"",false])";
                //condition = "((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"") or bb_admin_activated) and (this animationPhase ""dvere2"" >= 0.5)";
                statement = "this animate [""dvere2"", 0]";
            };
            //Esta y la otra estan cambiadas, cambiar la condicion de lugar vaya chapuzas los de bis
            class CloseDoors2 {
                displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_O_DOOR;
                position = "Open_vrata4";
                radius = 3;
                onlyForPlayer = 1;
                condition = "((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"") or bb_admin_activated) and (this animationPhase ""dvere2"" < 0.5)";
                //condition = "(this animationPhase ""dvere2"" < 0.5) and !(this getVariable[""bb_assaulted"",false])";
                statement = "this animate [""dvere2"", 1]";
            };
			
            class OpenDoors3 {
                displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_O_DOOR;
                position = "Open_vrata1";
                radius = 4;
                onlyForPlayer = 1;
                condition = "((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"") or bb_admin_activated) and (this animationPhase ""vrata1"" < 0.5)";
                statement = "this animate [""vrata1"", 1]";
            };
			
            class CloseDoors3 {
                displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_C_DOOR;
                position = "Open_vrata1";
                radius = 4;
                onlyForPlayer = 1;
                condition = " (this animationPhase ""vrata1"" >= 0.5) and !(this getVariable[""bb_assaulted"",false])";
                statement = "this animate [""vrata1"", 0]";
            };
			
            class OpenDoors4 {
                displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_O_DOOR;
                position = "Open_vrata2";
                radius = 4;
                onlyForPlayer = 1;
                condition = "((this getVariable[""ClanID"",""0""] == clanTag) and (this getVariable[""ClanID"",""0""] != ""0"") or bb_admin_activated) and (this animationPhase ""vrata2"" < 0.5)";
                statement = "this animate [""vrata2"", 1]";
            };
			
            class CloseDoors4 {
                displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
                displayName = $STR_DN_OUT_C_DOOR;
                position = "Open_vrata2";
                radius = 4;
                onlyForPlayer = 1;
                condition = " (this animationPhase ""vrata2"" >= 0.5) and !(this getVariable[""bb_assaulted"",false])";
                statement = "this animate [""vrata2"", 0]";
            };
        };
        actionBegin1 = "OpenDoors1";
        actionEnd1 = "OpenDoors1";
        actionBegin2 = "OpenDoors2";
        actionEnd2 = "OpenDoors2";
        actionBegin3 = "OpenDoors3";
        actionEnd3 = "OpenDoors3";
        actionBegin4 = "OpenDoors4";
        actionEnd4 = "OpenDoors4";
    };


    class Notebook;
    class BB_Portatil : Notebook {
        displayName = "Main panel";
        vehicleClass = "BB_Buildings";
        class UserActions {
			class Rude_Boy {
                displayName="Song: Dub Inc - Rudeboy";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_rudeboy""] spawn fnc_song_start;";
            };
			class song_hardwell {
                displayName="House - Hardwell";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_hardwell""] spawn fnc_song_start;";
            };
			class song_mp1 {
                displayName="Masterplan - Heart of Darkness";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_masterplan_hod""] spawn fnc_song_start;";
            };
			class song_mp2 {
                displayName="Masterplan - The Dark Road";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_masterplan_tdr""] spawn fnc_song_start;";
            };

			class song_WM {
                displayName="RTW - Warrior March";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_WM""] spawn fnc_song_start;";
            };
            class Song_Molinos {
                displayName="Song: Molinos de viento";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_molinos""] spawn fnc_song_start;";
            };
			class Song_BB_song_crom {
                displayName="Song: The Anvil Of Crom";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="!bb_song_activated and !([this] call fnc_check_song)"
                statement = "[this,""BB_song_crom""] spawn fnc_song_start;";
            };
            class Song_Stop {
                displayName="Stop song";
                onlyforplayer = "true";
                radius = 3;
                position ="action";
                condition="bb_song_activated or ([this] call fnc_check_song)"
                statement = "[this] spawn fnc_song_stop;";
            };
        };
    };

};
